# Generated by Django 4.0 on 2021-12-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_type',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog.post'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
